CREATE TABLE POST_MEMBER (

       MEMBER_NO NUMBER NOT NULL,
       MEMBER_ID VARCHAR2(50) UNIQUE,
       MEMBER_PW VARCHAR2(50) UNIQUE,
       MEMBER_NICKNAME VARCHAR(50) NOT NULL,
       ENROLL_DATE DATE DEFAULT SYSDATE,
       MEMBER_DEL CHAR(1) DEFAULT 'N',
       
      CONSTRAINT MEMBER_NO_CHECK PRIMARY KEY(MEMBER_NO)
);

INSERT INTO POST_MEMBER VALUES(SEQ_NUM.NEXTVAL, 'user01', 'pass01', '성기현', DEFAULT, DEFAULT);
INSERT INTO POST_MEMBER VALUES(SEQ_NUM.NEXTVAL, 'user02', 'pass02', '이정재', DEFAULT, DEFAULT);
INSERT INTO POST_MEMBER VALUES(SEQ_NUM.NEXTVAL, 'user03', 'pass03', '이성범', DEFAULT, DEFAULT);



SELECT * FROM POST_MEMBER;


-- 회원 전용 시퀀스
CREATE SEQUENCE SEQ_NUM
NOCACHE
NOCYCLE
START WITH 1;

SELECT SEQ_NUM.CURRVAL FROM DUAL;

-- 게시판 전용 시퀀스
CREATE SEQUENCE SEQ_POST_NUM
START WITH 1;

  SELECT POST_NO, POST_TITLE, POST_CONTENT, TO_CHAR(POST_DATE, 'YYYY"년"MM"월"DD"일" HH24"시"MI"분"SS"초"') AS POST_DATE, MEMBER_NO
   FROM POST
   WHERE POST_NO = 1 AND MEMBER_NO = 1;

CREATE TABLE POST (

  
    POST_NO NUMBER NOT NULL,
    POST_TITLE VARCHAR2(50),
    POST_CONTENT VARCHAR2(1000),
    POST_DATE DATE DEFAULT SYSDATE,
    POST_DEL CHAR(1) DEFAULT 'N',
    MEMBER_NO NUMBER,
    
    CONSTRAINT MEMBER_NO_FE FOREIGN KEY(MEMBER_NO) REFERENCES POST_MEMBER ON DELETE CASCADE
 

);

CREATE SEQUENCE FINAL_NUM
START WITH 6;


SELECT *
  FROM all_sequences
 WHERE sequence_name = 'SEQ_NUM';

CREATE SEQUENCE HI_NUM
START WITH 6;

SELECT * FROM POST;
SELECT * FROM POST_MEMBER;

DELETE FROM POST
WHERE POST_NO = 22;




COMMENT ON COLUMN POST.POST_NO IS '게시판 번호';
COMMENT ON COLUMN POST.POST_TITLE  IS '게시판 제목';
COMMENT ON COLUMN POST.POST_CONTENT  IS '게시판 내용';
COMMENT ON COLUMN POST.POST_DATE  IS '게시판 등록날짜';
COMMENT ON COLUMN POST.POST_DEL  IS '게시판 삭제여부';
COMMENT ON COLUMN POST.MEMBER_NO  IS '회원 번호';






